server:
  port: 8081
spring:
  application:
    name: expensez
  datasource:
    url: jdbc:postgresql://localhost:5432/my_database
    username: user
    password: user_password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        ddl-auto: update

