server:
  port: 8081
spring:
  application:
    name: expensez
  datasource:
    url: jdbc:postgresql://localhost:5432/my_database
    username: user
    password: user_password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
    default-schema: expensez
    schema: expensez
feature:
  use-mocks: false
