server:
  port: 8081
spring:
  application:
    name: expensez
  datasource:
    url: jdbc:postgresql://localhost:5432/my_database
    username: user
    password: user_password
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: update

