server:
  port: 8081
spring:
  application:
    name: expensez
  datasource:
    url: jdbc:postgresql://localhost:5432/my_database
    username: user
    password: user_password
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        ddl-auto: update

feature:
  use-mocks: false
